### ISSUE TITLE
bug getting keyring in 1-Deploy_Linode_Ceph_Cluster.sh

### ISSUE THREAD

**Issue by bengland2** [acalhounRH/automated_ceph_test#6]
This script tries to get the client.admin keyring but it doesn't work for RHCS 3.1.   ceph-ansible succeeded.

ceph_client_key=/ceph-ansible-keys/`ls /ceph-ansible-keys/ | grep -v conf`/etc/ceph/ceph.client.admin.keyring 
cp $ceph_client_key /etc/ceph/ceph.client.admin.keyring 

This doesn't work with RHCS 3.1.  My suggestion is copy your status check script over to $monname and run it there, then you don't need to install Ceph on the Jenkins Agent at all, just ceph-ansible, right?

cp: cannot stat ‘/ceph-ansible-keys//etc/ceph/ceph.client.admin.keyring’: No such file or directory
Traceback (most recent call last):
  File "/root/automated_ceph_test/scripts/utils/check_cluster_status.py", line 74, in <module>
    main()
  File "/root/automated_ceph_test/scripts/utils/check_cluster_status.py", line 11, in main
    new_client = ceph_client()
  File "/root/automated_ceph_test/scripts/utils/check_cluster_status.py", line 58, in __init__
    logger.exception("Connection error: %s" % e.strerror )
AttributeError: 'PermissionError' object has no attribute 'strerror'
+ status=1
/tmp/jenkins5620137425889468234.sh: line 22: unexpected EOF while looking for matching `"'

**Comment by acalhounRH** [comment]
This issue has be resolved on lined deployments, although may need to be evaluated for non-linode deployments as well. keeping this issue open, until verified solution is working in non-linode deployments

**Comment by acalhounRH** [comment]
This has been resolved with the rework of 1-Deploy_Ceph_Cluster.sh
